apiVersion: apps/v1
kind: Deployment 
metadata:
  name: node-app-deployment-clusterip
spec: 
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - image: muralisocial123/node-app-example:latest
          name: node-app-cont 
          ports:
            - containerPort: 3000
  replicas: 2
  selector:
    matchLabels:
      app: node-app