apiVersion: apps/v1
kind: Deployment 
metadata:
  name: node-app-deployment-clusterip
spec: 
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - image: muralisocial123/node-app-example:latest
          name: node-app-cont 
          ports:
            - containerPort: 3000
  replicas: 2
  selector:
    matchLabels:
      app: node-app
---
apiVersion: v1 
kind: Service 
metadata:
  name: node-clusterip 
spec:
  ports:
    - port: 3004
      targetPort: 3000 
      protocol: TCP
  selector: 
    app: node-app
  type: ClusterIP   
          