apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: resto-app-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      web: resto
  template:
    metadata:
      labels:
        web: resto 
    spec:
      containers:
        - image: muralisocial123/resto-image:latest
          name: resto-web 
          ports:
            - containerPort: 80