apiVersion: v1 
kind: Pod 
metadata:
  name: nginx-pod 
  namespace: test-ns 
spec: 
  containers:
    - image: nginx:latest 
      name: nginx-app 
      ports:
        - containerPort: 80 
    - image: muralisocial123/resto-image:latest
      name: rest-app
      ports:
        - containerPort: 80      
