apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: node-app-transaction
spec: 
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - image: muralisocial123/node-app-example:latest
          name: node-app-cont
          ports:
            - containerPort: 3000    
  replicas: 1
  selector:
    matchLabels:
      app: node-app          
---
apiVersion: v1 
kind: Service 
metadata:
  name: node-svc-example
spec:
  selector:  
    app: node-app
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP 
  type: NodePort      