apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: node-port-deployment 
  labels:
    app: ecommerce 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels: 
        app: node
    spec:
      containers:
        - image: muralisocial123/ecommerce-web:latest
          name: ecommerce-web 
          ports:
            - containerPort: 80
---
apiVersion: v1 
kind: Service    
metadata:
  name: nodeport-svc
spec:
  selector:
    app: ecommerce
  ports:
    - port: 82 
      targetPort: 80
      protocol: TCP 
  type: NodePort    

              

   

