apiVersion: v1 
kind: Pod 
metadata:
  name: node-app-example
spec:
  containers:
    - name: node-example
      image: muralisocial123/node-app-example:latest
      ports:
        - containerPort: 3000
 
