apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: node-app-deployment 
spec: 
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - image: nginx:latest
          name: node-app-cont
          ports:
            - containerPort: 80    
  replicas: 1
  selector:
    matchLabels:
      app: node            
---
apiVersion: v1 
kind: Service 
metadata:
  name: node-svc 
spec:
  selector:  
    app: node 
  ports:
    - port: 83
      targetPort: 80
      protocol: TCP 
  type: NodePort      