apiVersion: v1 
kind: Pod 
metadata:
  name: test-ecommerce-web 
  namespace: test-ns 
spec: 
  - name: test-ecommerce 
    image: muralisocial123/ecommerce-image:1.0
    ports:
      - containerPort: 80  