apiVersion: v1 
kind: Pod 
metadata:
  name: simple-pod 
spec:
  restartPolicy: Never
  containers:
    - image: muralisocial123/transcation-app:latest
      name: transaction-app
      volumeMounts:
        - name: s-volume
          mountPath: /output
  volumes:
    - name: s-volume
      persistentVolumeClaim:
        claimName: simple-pvc